#  Logistic Regression Test  StatsModels VS SAS 

In [1]:
from __future__ import print_function
import numpy as np
import statsmodels.api as sm
import scipy.stats as stats
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
data = pd.read_csv('/home/dzn/Project/d05_scorecard/d01_LogisticRegression/data/x.csv', sep = ',')


In [3]:
df = sm.add_constant(data, prepend=True)


In [4]:
df.head()


const  cell  smear  infil   li  blast   temp  y
0      1   0.8   0.83   0.66  1.9  1.100  0.996  1
1      1   0.9   0.36   0.32  1.4  0.740  0.992  1
2      1   0.8   0.88   0.70  0.8  0.176  0.982  0
3      1   1.0   0.87   0.87  0.7  1.053  0.986  0
4      1   0.9   0.75   0.68  1.3  0.519  0.980  1

In [56]:
xcol = ['const', 'cell']
aa = np.vstack((df.const, df.cell))

In [66]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
c = np.vstack((a,b))
c

array([[1, 2, 3],
       [2, 3, 4]])

In [67]:
np.vstack((c,a))

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3]])

In [ ]:
bb = pd.DataFrame(aa.T, columns = xcol)


In [46]:
aa.index(max(aa))

3

In [22]:
type(df.iloc[:,0:7])

pandas.core.frame.DataFrame

In [39]:
df.y

0     1
1     1
2     0
3     0
4     1
5     0
6     1
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    1
16    0
17    0
18    0
19    1
20    0
21    0
22    1
23    0
24    1
25    1
26    0
Name: y, dtype: int64

In [33]:
logit_mod = sm.Logit(df.y, bb)


In [6]:
logit_mod = sm.Logit(df.y, df.const)


In [7]:
logit_res = logit_mod.fit(disp=1)


Optimization terminated successfully.
         Current function value: 0.636514
         Iterations 4


In [9]:
print(logit_res.summary())


                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:                   27
Model:                          Logit   Df Residuals:                       26
Method:                           MLE   Df Model:                            0
Date:                Mon, 18 Jan 2016   Pseudo R-squ.:                   0.000
Time:                        11:33:11   Log-Likelihood:                -17.186
converged:                       True   LL-Null:                       -17.186
                                        LLR p-value:                       nan
                 coef    std err          z      P>|z|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const         -0.6931      0.408     -1.698      0.090        -1.493     0.107


In [31]:
logit_res.params


const   -0.693147
dtype: float64

In [11]:
logit_res.aic


36.37176508791989

In [12]:
logit_res.llf


-17.185882543959945

In [13]:
logit_res.llr_pvalue


nan

In [14]:
logit_res.llr


-0.0

In [30]:
logit_res.bse


const    0.408248
dtype: float64

In [16]:
logit_res.df_resid


26.0

In [28]:
logit_res.llr


-0.0

In [18]:
logit_res.df_model


0.0

In [20]:
WaldChi_Square = (logit_res.params[0]/logit_res.bse[0])**2


In [33]:
np.abs(-WaldChi_Square)


2.8827180835092121

In [38]:
2*stats.norm.cdf(-np.abs((logit_res.params[0]/logit_res.bse[0])))


0.089534771877787134

In [3]:
np.ones(3)

array([ 1.,  1.,  1.])

In [4]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [40]:
 xenter= ['const']

In [50]:
aa = xenter + ['123']


In [53]:
del aa[0] 

In [54]:
aa

['123']

In [5]:
import logitregression as logit
import pandas as pd

In [6]:
data  = pd.read_csv('/home/dzn/Project/d05_scorecard/d01_LogisticRegression/data/x.csv', sep = ',')
role  = [1,1,1,1,1,1,2]
a = logit.StepwiseModel(data, role, slentry=0.3, slstay=0.2)
a.beta()

**** The LogitReg Process ****

** Step 0. Intercept entered:

                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:                   27
Model:                          Logit   Df Residuals:                       26
Method:                           MLE   Df Model:                            0
Date:                Wed, 20 Jan 2016   Pseudo R-squ.:                   0.000
Time:                        15:27:47   Log-Likelihood:                -17.186
converged:                       True   LL-Null:                       -17.186
                                        LLR p-value:                       nan
                 coef    std err          z      P>|z|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const         -0.6931      0.408     -1.698      0.090        -1.493     0.107
 
                          Model Fit Statistics 
AIC               

{'const': -3.7771401577554227, 'li': 2.8972638566733577}